### ISSUE TITLE
Error npm start

### ISSUE THREAD

**Issue by BWakonig** [webdesignio/webdesignio-cli#5]
`eduroamstud-130-82-254-191:designio` benediktwakonig$ webdesignio init 

```
web-design.io • commander
  - ready to take off -

I need your credentials on https://webdesignio.com
to log you in or register a brand-new account.
```

E-Mail: benedikt.wakonig@gmail.com
Password: ********

Attempting registration ... exists
Fetching token ... done

```
✓ Successfully initialized test
  Use `npm start` to get up and running
```

eduroamstud-130-82-254-191:designio benediktwakonig$ npm start

> test@1.0.0 start /Users/benediktwakonig/designio
> node scripts/start

module.js:457
    throw err;
    ^

Error: Cannot find module '/Users/benediktwakonig/designio/scripts/start'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Darwin 14.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! test@1.0.0 start: `node scripts/start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the test@1.0.0 start script 'node scripts/start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the test package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs test
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls test
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/benediktwakonig/designio/npm-debug.log
`eduroamstud-130-82-254-191:designio benediktwakonig$ webdesignio init 

```
web-design.io • commander
  - ready to take off -

I need your credentials on https://webdesignio.com
to log you in or register a brand-new account.
```

E-Mail: benedikt.wakonig@gmail.com
Password: ********

Attempting registration ... exists
Fetching token ... done

```
✓ Successfully initialized test
  Use `npm start` to get up and running
```

eduroamstud-130-82-254-191:designio benediktwakonig$ npm start

> test@1.0.0 start /Users/benediktwakonig/designio
> node scripts/start

module.js:457
    throw err;
    ^

Error: Cannot find module '/Users/benediktwakonig/designio/scripts/start'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Darwin 14.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! test@1.0.0 start: `node scripts/start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the test@1.0.0 start script 'node scripts/start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the test package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs test
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls test
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/benediktwakonig/designio/npm-debug.log
`

**Comment by domachine** [comment]
Hi, thank you so much for testing webdesignio. I'm afraid, you have to initialize your website like this:

`webdesignio init mywebsite`

`mywebsite` is the name of your website. You can use whichever name you want but please use lower-case characters without spaces or special chars.

If you invoke `webdesignio init` without argument, it attempts to initialize your current directory. It assumes that you already checked out the boilerplate, but I think you haven't. If you invoke it with an argument it will properly checkout the boilerplate and initialize a new website.

Hope this helps.

**Comment by BWakonig** [comment]
when `webdesignio init mywebsite` it init mywebsite in sites but this happens

```
eduroamstud-130-82-254-191:~ benediktwakonig$ node -v
v6.6.0
eduroamstud-130-82-254-191:~ benediktwakonig$ cd sites
eduroamstud-130-82-254-191:sites benediktwakonig$ su root
Password:
sh-3.2# npm install -g @webdesignio/cli@0.9.3
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash.assign@4.2.0: This package is deprecated. Use Object.assign.
/usr/local/bin/webdesignio -> /usr/local/lib/node_modules/@webdesignio/cli/bin/cli.js
/usr/local/lib
└── @webdesignio/cli@0.9.3 

sh-3.2# webdesignio init mywebsite

    web-design.io • commander
      - ready to take off -

▹▹▹▹▹ Fetching boilerplate ...  ⚠  [Error]  invalid distance too far back

    > Something went wrong, check the errors above and try again.
    > Let us know, if you know a better error message.
    > https://github.com/webdesignio/webdesignio-cli

```

<img width="1440" alt="bildschirmfoto 2016-10-03 um 15 01 01" src="https://cloud.githubusercontent.com/assets/22446784/19038108/50281d38-897a-11e6-953b-a917804c875d.png">

**Comment by domachine** [comment]
Ok, seems that the download from github failed. I already experienced cases when github returned corrupted files on download. Just delete the directory `mywebsite` and retry. Very soon we will switch to cloning the files using `git` so that this becomes more stable.

Sorry for inconvenience. Maybe you wanna join our slack channel, so we can chat in realtime for questions: https://webdesignio-community.herokuapp.com.
